#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Run following command from ansible base for optimal use of this playbook:
# ansible-playbook -i inventory.ini playbooks/iosxe_verify_config.yml --ask-vault-pass --diff
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# --ask-vault-pass is needed to let ansible decrypt secrets needed to access the Cisco switches
# --diff will show and log the changes you have made to the running config

---
- name: "PLAY 1: Compare config Cisco IOS-XE device with master config."
  connection: network_cli
  hosts: R5
  gather_facts: no
  tasks:

    - name: "TASK 1: Open up vault files."
      include_vars: "../files/secrets_fault.yml"
      delegate_to: localhost

    - name: "TASK 2: Compare the running-config against master config."
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', '../files/config_backup/R5_config.cfg') }}"
      register: output
...