#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Run following command from ansible base for optimal use of this playbook:
# ansible-playbook -i inventory.ini playbooks/iosxe_send_config_radius_eap.yml --ask-vault-pass --diff
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# --ask-vault-pass is needed to let ansible decrypt secrets needed to access the Cisco switches.
# --diff will show and log the changes you have made to the running config.
#
#This playbook  is written do deal with the below prompt when configuring class maps for eap:
#This operation will permanently convert all relevant authentication commands to their CPL control-policy equivalents.As this conversion is irreversible and will disable the conversion
#CLI 'authentication display [legacy|new-style]', you are strongly advised to back up your current configuration before proceeding. Do you wish to continue? [yes]: yes

---
- name: "PLAY 1: Send configuration to a Cisco IOS-XE device"
  connection: network_cli
  hosts: R5
  gather_facts: no
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H%M') }}"
  tasks:

    - name: "TASK 1: Open up vault files."
      include_vars: "../files/secrets_fault.yml"
      delegate_to: localhost

    - name: "TASK 2 : Run commands that require answering a prompt."
      cisco.ios.ios_command:
        commands:
          - command: "config t"
          - command: "class-map type control subscriber match-all AAA_SVR_DOWN_AUTHD_HOST"
            prompt: "yes"
            answer: "yes"
      register: output

    - name: "TASK 3 : Print out prompt interaction."
      debug:
        msg: "{{ output }}"

    - name: "TASK 4: Backup config and configure device wiht config in template file, after save configuration."
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: ./files/config_backup/
          filename: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}-config-{{ timestamp }}.cfg"
        src: "../files/config_generated/R4_config.cfg"
        match: exact
        diff_against: running
        save_when: modified
...